---
title: Redis SSL support via environment variables
category: added
author: Jose Javier Merchante <jjmerchante@bitergia.com>
issue: 985
notes: >
  Adds support for secure Redis connections over SSL. It can
  be configured using the following environment variables.
  SORTINGHAT_REDIS_SSL, SORTINGHAT_REDIS_SSL_CERT_REQS,
  SORTINGHAT_REDIS_SSL_CA_CERTS, SORTINGHAT_REDIS_SSL_CERTFILE,
  SORTINGHAT_REDIS_SSL_KEYFILE.
